name: Openfire CI

env:
  CI: true

on: [push, pull_request]

jobs:
  build:

    name: Build Openfire from source
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 1.8, 11 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Maven repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-java${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-java${{ matrix.java }}-maven-
            ${{ runner.os }}-
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload distribution
        uses: actions/upload-artifact@v2
        with:
          name: distribution-java${{ matrix.java }}
          path: distribution/target/distribution-base
      - name: Upload test files
        uses: actions/upload-artifact@v2
        with:
          name: test-files
          path: |
            runConnectivityIntegrationTests
            test.gradle

  connectivity:

    name: Execute Connectivity CI tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download distribution artifact from build job.
        uses: actions/download-artifact@v2
        with:
          name: distribution-java1.8
          path: distribution/target/distribution-base
      - name: Download test files from build job.
        uses: actions/download-artifact@v2
        with:
          name: test-files
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Fix file permissions
        run: |
          chmod +x distribution/target/distribution-base/bin/openfire.sh
          chmod +x ./runConnectivityIntegrationTests
      - name: Run connectivity tests
        run: ./runConnectivityIntegrationTests -d -l -i 127.0.0.1
      - name: Run connectivity tests again
        run: ./runConnectivityIntegrationTests -d -l -i 127.0.0.1
      - name: Run connectivity tests once more
        run: ./runConnectivityIntegrationTests -d -l -i 127.0.0.1
      - name: Run connectivity tests for good measure
        run: ./runConnectivityIntegrationTests -d -l -i 127.0.0.1
